### ISSUE TITLE
TypeError: ne() received an invalid combination of arguments - got (NoneType)

### ISSUE THREAD

**Issue by QimingLi-scir** [LLaVA-VL/LLaVA-NeXT#117]
when i run bash , error occurs
> bash scripts/video/demo/video_demo.sh /data/checkpoints/llama3-llava-next-8b vicuna_v1 32 2 average after no_token True /mnt/data/user/tc_agi/qmli/LLaVA-NeXT-inference/LLaVA-NeXT-inference/playground/demo/xU25MMA2N4aVtYay.mp4

Traceback (most recent call last):
  File "/mnt/data/user/tc_agi/qmli/LLaVA-NeXT-inference/LLaVA-NeXT-inference/playground/demo/video_demo.py", line 316, in <module>
    run_inference(args)
  File "/mnt/data/user/tc_agi/qmli/LLaVA-NeXT-inference/LLaVA-NeXT-inference/playground/demo/video_demo.py", line 209, in run_inference
    attention_masks = input_ids.ne(tokenizer.pad_token_id).long().cuda()
TypeError: ne() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (Number other)
      didn't match because some of the arguments have invalid types: (NoneType)

how can i solve this problem?

**Comment by LetsGoFir** [comment]
same problem

**Comment by HuangChiEn** [comment]
add following code snippet, after `llava.train.train.py` Line 1568 : 
Namely, after this line : https://github.com/LLaVA-VL/LLaVA-NeXT/blob/09e5840d5589ad2d6a8656c0a60f21ae134b3309/llava/train/train.py#L1568

```
# hack for the LLaMA 3 using Qwen tokenizer, by default Qwen doesn't have a pad token but we can assign it EOT as pad. 
# more information: https://github.com/QwenLM/Qwen/blob/main/tokenization_note.md
logging.warn(f"Model name: {model_args.model_name_or_path.lower()}")
logging.warn("Making the new pad token for the tokenizer")
# this is the hack you need because later in the logic, it adds the unk token
tokenizer.pad_token='<|eot_id|>'
tokenizer.unk_token='<|eot_id|>'
logging.warn(f"Tokenizer pad token! {tokenizer.pad_token}")

```
