### ISSUE TITLE
运行llava-next-video的eval示例脚本报错

### ISSUE THREAD

**Issue by yutao1024** [LLaVA-VL/LLaVA-NeXT#248]
Traceback (most recent call last):
  File "/home/ubuntu/taoyu/LLaVA-NeXT/llava/eval/model_video_detail_description.py", line 197, in <module>
    run_inference(args)
  File "/home/ubuntu/taoyu/LLaVA-NeXT/llava/eval/model_video_detail_description.py", line 175, in run_inference
    model.update_prompt([[cur_prompt]])
  File "/home/ubuntu/miniconda3/envs/llava/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1695, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'LlavaLlamaForCausalLM' object has no attribute 'update_prompt'

**Comment by ZhangYuanhan-AI** [comment]
Hi, we recommend use [lmms-eval](https://github.com/EvolvingLMMs-Lab/lmms-eval) for the evaluation of the videoDC.

**Comment by ZhangYuanhan-AI** [comment]
Using README here: https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/docs/LLaVA-NeXT-Video_0716.md
