### ISSUE TITLE
how to merge lora finetuned model with base model 

### ISSUE THREAD

**Issue by jiepan874** [LLaVA-VL/LLaVA-NeXT#253]
I finetune llava-one-vision using lmms-lab/llava-onevision-qwen2-7b-ov by config --lora_enable True --lora_r 128 --lora_alpha 256 --mm_projector_lr 2e-5  and have checkpoint saved, how can i using this model for eval?
![image](https://github.com/user-attachments/assets/4a962bbf-64ac-49e3-a49a-8565cb34d1b0)

**Comment by lxr-1204** [comment]
I tried merging using the following code, but I got garbled results, and I’m not sure if it’s an issue with my training or the merging process. If you’d like, we can discuss it further.
`    tokenizer, model, image_processor, context_len = load_pretrained_model(model_path, args.model_base, model_name, overwrite_config=overwrite_config)
`
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/008070ca-8c46-4fc9-8d45-3229ecafb1b0">

**Comment by jb892** [comment]
I've encountered the same issue. Full-parameter fine-tuning works perfectly, but LoRA fine-tuning produces garbled results. I'm attempting to migrate my project from the zjysteven/lmms-finetune repository, where LoRA fine-tuning works correctly.

**Comment by haozhang1234** [comment]
bro, can you take a look at the config configuration that Lora has fine tuned? Why does it show that the weight shapes do not match when I merge Lora weights.
This is an error in my output：
You are using a model of type siglip to instantiate a model of type clip_vision_model. This is not supported for all configurations of models and can yield errors.
Traceback (most recent call last):
  File "/4T/WK/MyProjects/LLaVA-NeXT/scripts/archived/merge_lora_weights.py", line 22, in <module>
    merge_lora(args)
  File "/4T/WK/MyProjects/LLaVA-NeXT/scripts/archived/merge_lora_weights.py", line 8, in merge_lora
    tokenizer, model, image_processor, context_len = load_pretrained_model(args.model_path, args.model_base, model_name, device_map="cpu")
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/builder.py", line 87, in load_pretrained_model
    model = LlavaQwenForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True,config=lora_cfg_pretrained,attn_implementation=attn_implementation, **kwargs)
  File "/home/wk/anaconda3/envs/llava-next/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3404, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/language_model/llava_qwen.py", line 55, in __init__
    self.model = LlavaQwenModel(config)
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/language_model/llava_qwen.py", line 43, in __init__
    super(LlavaQwenModel, self).__init__(config)
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/llava_arch.py", line 41, in __init__
    self.vision_tower = build_vision_tower(config, delay_load=delay_load)
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/multimodal_encoder/builder.py", line 23, in build_vision_tower
    return CLIPVisionTower(vision_tower, args=vision_tower_cfg, **kwargs)
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/multimodal_encoder/clip_encoder.py", line 24, in __init__
    self.load_model()
  File "/4T/WK/MyProjects/LLaVA-NeXT/llava/model/multimodal_encoder/clip_encoder.py", line 41, in load_model
    self.vision_tower = CLIPVisionModel.from_pretrained(self.vision_tower_name, device_map=device_map)
  File "/home/wk/anaconda3/envs/llava-next/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3531, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/wk/anaconda3/envs/llava-next/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4009, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for CLIPVisionModel:
        size mismatch for vision_model.embeddings.patch_embedding.weight: copying a param with shape torch.Size([1152, 3, 14, 14]) from checkpoint, the shape in current model is torch.Size([768, 3, 32, 32]).
        size mismatch for vision_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([729, 1152]) from checkpoint, the shape in current model is torch.Size([50, 768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.k_proj.weight: copying a param with shape torch.Size([1152, 1152]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.k_proj.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.v_proj.weight: copying a param with shape torch.Size([1152, 1152]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.v_proj.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.q_proj.weight: copying a param with shape torch.Size([1152, 1152]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.q_proj.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.out_proj.weight: copying a param with shape torch.Size([1152, 1152]) from checkpoint, the shape in current model is torch.Size([768, 768]).
        size mismatch for vision_model.encoder.layers.0.self_attn.out_proj.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.layer_norm1.weight: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.layer_norm1.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).
        size mismatch for vision_model.encoder.layers.0.mlp.fc1.weight: copying a param with shape torch.Size([4304, 1152]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
        size mismatch for vision_model.encoder.layers.0.mlp.fc1.bias: copying a param with shape torch.Size([4304]) from checkpoint, the shape in current model is torch.Size([3072]).
        size mismatch for vision_model.encoder.layers.0.mlp.fc2.weight: copying a param with shape torch.Size([1152, 4304]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
        size mismatch for vision_model.encoder.layers.0.mlp.fc2.bias: copying a param with shape torch.Size([1152]) from checkpoint, the shape in current model is torch.Size([768]).

**Comment by jb892** [comment]
It seems that you have loaded the wrong vision tower ckpt. Can you provide the config.json and your input parameter for `merge_lora_weights.py`

**Comment by haozhang1234** [comment]
Here is the configuration for my models - lmms lab - llava review qwen2-0.5b-ov:
{
  "_name_or_path": "/4T/WK/MyProjects/LLaVA-NeXT/llava-model/models--lmms-lab--llava-onevision-qwen2-0.5b-ov",
  "architectures": [
    "LlavaQwenForCausalLM"
  ],
  "attention_dropout": 0.0,
  "mm_newline_position":"one_token",
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "hidden_act": "silu",
  "hidden_size": 896,
  "image_aspect_ratio": "anyres_max_9",
  "image_crop_resolution": null,
  "image_grid_pinpoints": [
    [
      384,
      384
    ],
    [
      384,
      768
    ],
    [
      384,
      1152
    ],
    [
      384,
      1536
    ],
    [
      384,
      1920
    ],
    [
      384,
      2304
    ],
    [
      768,
      384
    ],
    [
      768,
      768
    ],
    [
      768,
      1152
    ],
    [
      768,
      1536
    ],
    [
      768,
      1920
    ],
    [
      768,
      2304
    ],
    [
      1152,
      384
    ],
    [
      1152,
      768
    ],
    [
      1152,
      1152
    ],
    [
      1152,
      1536
    ],
    [
      1152,
      1920
    ],
    [
      1152,
      2304
    ],
    [
      1536,
      384
    ],
    [
      1536,
      768
    ],
    [
      1536,
      1152
    ],
    [
      1536,
      1536
    ],
    [
      1536,
      1920
    ],
    [
      1536,
      2304
    ],
    [
      1920,
      384
    ],
    [
      1920,
      768
    ],
    [
      1920,
      1152
    ],
    [
      1920,
      1536
    ],
    [
      1920,
      1920
    ],
    [
      1920,
      2304
    ],
    [
      2304,
      384
    ],
    [
      2304,
      768
    ],
    [
      2304,
      1152
    ],
    [
      2304,
      1536
    ],
    [
      2304,
      1920
    ],
    [
      2304,
      2304
    ]
  ],
  "image_split_resolution": null,
  "image_token_index": 151646,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "mm_hidden_size": 1152,
  "mm_patch_merge_type": "spatial_unpad",
  "mm_projector_lr": null,
  "mm_projector_type": "mlp2x_gelu",
  "mm_resampler_type": null,
  "mm_spatial_pool_mode": "bilinear",
  "mm_tunable_parts": "mm_vision_tower,mm_mlp_adapter,mm_language_model",
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower": "google/siglip-so400m-patch14-384",
  "mm_vision_tower_lr": 2e-06,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pos_skipping_range": 4096,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 32768,
  "tie_word_embeddings": true,
  "tokenizer_model_max_length": 32768,
  "tokenizer_padding_side": "right",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.40.0.dev0",
  "use_cache": true,
  "use_mm_proj": true,
  "use_pos_skipping": false,
  "use_sliding_window": false,
  "vision_tower_pretrained": null,
  "vocab_size": 151936
}
According to the official issue mentioned, I have changed the "model_type" from "llava" to "qwen2" to facilitate fine-tuning of the model.
This is the parameter input for my merger lora_weights. py
python /4T/WK/MyProjects/LLaVA-NeXT/scripts/archived/merge_lora_weights.py \
    --model-path /4T/WK/MyProjects/LLaVA-NeXT/checkpoints/lora_model/llava-onevision-._llava-model_models--google--siglip-so400m-patch14-384-._llava-model_models--Qwen--Qwen2-0.5B-Instruct-ov_stage_video_detail_lora \
    --model-base /4T/WK/MyProjects/LLaVA-NeXT/llava-model/models--lmms-lab--llava-onevision-qwen2-0.5b-ov \
    --save-model-path /4T/WK/MyProjects/LLaVA-NeXT/checkpoints/lora_merge_model/test/
    
But I think the problem may have been with CLIPVisionTower instead of SigLipVisionTower when the model was loaded during fine-tuning from the beginning. Because there is a situation where the dimensions do not correspond when merging models.Do you know how this was modified?

**Comment by haozhang1234** [comment]
This is the config that my Lora has fine tuned
{
  "_name_or_path": "./llava-model/models--lmms-lab--llava-onevision-qwen2-0.5b-ov",
  "add_faster_video": false,
  "add_time_instruction": false,
  "architectures": [
    "LlavaQwenForCausalLM"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 151643,
  "eos_token_id": 151645,
  "faster_token_stride": 10,
  "force_sample": false,
  "hidden_act": "silu",
  "hidden_size": 896,
  "image_aspect_ratio": "anyres_max_9",
  "image_crop_resolution": null,
  "image_grid_pinpoints": [
    [
      384,
      384
    ],
    [
      384,
      768
    ],
    [
      384,
      1152
    ],
    [
      384,
      1536
    ],
    [
      384,
      1920
    ],
    [
      384,
      2304
    ],
    [
      768,
      384
    ],
    [
      768,
      768
    ],
    [
      768,
      1152
    ],
    [
      768,
      1536
    ],
    [
      768,
      1920
    ],
    [
      768,
      2304
    ],
    [
      1152,
      384
    ],
    [
      1152,
      768
    ],
    [
      1152,
      1152
    ],
    [
      1152,
      1536
    ],
    [
      1152,
      1920
    ],
    [
      1152,
      2304
    ],
    [
      1536,
      384
    ],
    [
      1536,
      768
    ],
    [
      1536,
      1152
    ],
    [
      1536,
      1536
    ],
    [
      1536,
      1920
    ],
    [
      1536,
      2304
    ],
    [
      1920,
      384
    ],
    [
      1920,
      768
    ],
    [
      1920,
      1152
    ],
    [
      1920,
      1536
    ],
    [
      1920,
      1920
    ],
    [
      1920,
      2304
    ],
    [
      2304,
      384
    ],
    [
      2304,
      768
    ],
    [
      2304,
      1152
    ],
    [
      2304,
      1536
    ],
    [
      2304,
      1920
    ],
    [
      2304,
      2304
    ]
  ],
  "image_split_resolution": null,
  "image_token_index": 151646,
  "initializer_range": 0.02,
  "intermediate_size": 4864,
  "max_position_embeddings": 32768,
  "max_window_layers": 24,
  "mm_hidden_size": 1152,
  "mm_newline_position": "grid",
  "mm_patch_merge_type": "spatial_unpad",
  "mm_projector_lr": 5e-05,
  "mm_projector_type": "mlp2x_gelu",
  "mm_resampler_type": null,
  "mm_spatial_pool_mode": "bilinear",
  "mm_spatial_pool_stride": null,
  "mm_tunable_parts": "mm_vision_tower,mm_mlp_adapter,mm_language_model",
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower": "./llava-model/models--google--siglip-so400m-patch14-384",
  "mm_vision_tower_lr": 2e-06,
  "model_type": "qwen2",
  "num_attention_heads": 14,
  "num_hidden_layers": 24,
  "num_key_value_heads": 2,
  "pos_skipping_range": 4096,
  "rms_norm_eps": 1e-06,
  "rope_scaling": null,
  "rope_theta": 1000000.0,
  "sliding_window": 32768,
  "tie_word_embeddings": true,
  "tokenizer_model_max_length": 32768,
  "tokenizer_padding_side": "right",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.40.0.dev0",
  "use_cache": true,
  "use_mm_proj": true,
  "use_pos_skipping": false,
  "use_sliding_window": false,
  "vision_tower_pretrained": null,
  "vocab_size": 151936
}

**Comment by jb892** [comment]
<img width="1100" alt="image" src="https://github.com/user-attachments/assets/3d2195ae-4358-4811-b62f-aac484e941ca">

You may take a look of the `build_vision_tower` function , [line#23](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/333d6fc705f8b62325c61fda70a629cdfcf54129/llava/model/multimodal_encoder/builder.py#L21) should be executed based on your config: `return SigLipVisionTower(vision_tower, vision_tower_cfg=vision_tower_cfg, **kwargs)`. Clearly, there is something wrong with the vision tower building process.

In addition, have you checked the trainable params when do lora fine tune? I found that if your print out all trainable params at this line [llava/train/train.py#L1695](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/333d6fc705f8b62325c61fda70a629cdfcf54129/llava/train/train.py#L1695), just before training, it will show up many unwanted params that should be freezed. So, I would suggest you to re-order the train code a bit to avoid this error.

**Comment by zhudongwork** [comment]
> I've encountered the same issue. Full-parameter fine-tuning works perfectly, but LoRA fine-tuning produces garbled results. I'm attempting to migrate my project from the zjysteven/lmms-finetune repository, where LoRA fine-tuning works correctly.

I've encountered the same issue. Have you resolved it?

**Comment by jb892** [comment]
> Quote reply

@zhudongwork Not yet. However, I believe this lora bug is correlated to at least two issues I found,

**Comment by zhudongwork** [comment]
> > In addition, have you checked the trainable params when do lora fine tune? I found that if your print out all trainable params at this line [llava/train/train.py#L1695](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/333d6fc705f8b62325c61fda70a629cdfcf54129/llava/train/train.py#L1695), just before training, it will show up many unwanted params that should be freezed. So, I would suggest you to re-order the train code a bit to avoid this error.
> 
> @zhudongwork Not yet. I'm currently working on something more urgent. However, I believe this LoRA bug is related to at least two issues I've identified:
> 
> 1. There are problems with the trainable parameters in the above reply.
> 2. The PEFT version should be updated to 0.12.0.
>    Please let me know if you discover anything further. I will continue to debug this issue as soon as I am available.

What was the GPU usage like during your LoRA fine-tuning? I'm fine-tuning a 7B model with multiple GPUs, and each card is using over 75+ GB of GPU. Moreover, the trained model weights are also quite large, which doesn't seem to match the resource consumption expected from a typical LoRA fine-tuning. Have you encountered a similar issue?

**Comment by zhudongwork** [comment]
> > In addition, have you checked the trainable params when do lora fine tune? I found that if your print out all trainable params at this line [llava/train/train.py#L1695](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/333d6fc705f8b62325c61fda70a629cdfcf54129/llava/train/train.py#L1695), just before training, it will show up many unwanted params that should be freezed. So, I would suggest you to re-order the train code a bit to avoid this error.
> 
> @zhudongwork Not yet. I'm currently working on something more urgent. However, I believe this LoRA bug is related to at least two issues I've identified:
> 
> 1. There are problems with the trainable parameters in the above reply.
> 2. The PEFT version should be updated to 0.12.0.
>    Please let me know if you discover anything further. I will continue to debug this issue as soon as I am available.

I use the peft==0.12.0

**Comment by jb892** [comment]
That's way more VRAM consumption than expected. The exact VRAM usage  of my experiment has lost. However, you can try this code snippet at [llava/train/train.py#L1695](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/333d6fc705f8b62325c61fda70a629cdfcf54129/llava/train/train.py#L1695), you will find out the param issue.
```python
def count_trainable_parameters(model):
    lora_params = []
    non_lora_params = []

    for name, param in model.named_parameters():
        if param.requires_grad:
            if 'lora' in name.lower():
                lora_params.append((name, param))
            else:
                non_lora_params.append((name, param))

    lora_param_count = sum(param.numel() for _, param in lora_params)
    non_lora_param_count = sum(param.numel() for _, param in non_lora_params)

    print("Trainable parameters summary:")
    print(f"  LoRA parameters: {lora_param_count:,}")
    print(f"  Non-LoRA parameters: {non_lora_param_count:,}")
    print(f"  Total trainable parameters: {lora_param_count + non_lora_param_count:,}")

    print("\nDetails:")
    print("LoRA parameters:")
    for name, param in lora_params:
        print(f"  {name}: shape={param.shape}, numel={param.numel():,}")

    print("\nNon-LoRA parameters:")
    for name, param in non_lora_params:
        print(f"  {name}: shape={param.shape}, numel={param.numel():,}")

# Usage
count_trainable_parameters(model)
```

To solve this, you could just move following code block which init lora params
```python
    if training_args.lora_enable:
        from peft import LoraConfig, get_peft_model

        lora_config = LoraConfig(
            r=training_args.lora_r,
            lora_alpha=training_args.lora_alpha,
            target_modules=find_all_linear_names(model),
            lora_dropout=training_args.lora_dropout,
            bias=training_args.lora_bias,
            task_type="CAUSAL_LM",
        )
        if training_args.bits == 16:
            if training_args.bf16:
                model.to(torch.bfloat16)
            if training_args.fp16:
                model.to(torch.float16)
        rank0_print("Adding LoRA adapters...")
        model = get_peft_model(model, lora_config)
    
    if training_args.gradient_checkpointing:
        if hasattr(model, "enable_input_require_grads"):
            model.enable_input_require_grads()
        else:

            def make_inputs_require_grad(module, input, output):
                output.requires_grad_(True)

            model.get_input_embeddings().register_forward_hook(make_inputs_require_grad)
```
to just before data module init function `data_module = make_supervised_data_module(tokenizer=tokenizer, data_args=data_args)`

It will solve the trainable lora param issue.

**Comment by lxr-1204** [comment]
🎉 I might have solved this problem. 
* I rewrote the merge method, you can use this method instead of `load_pretrained_model` in `LLaVA-NeXT/llava/model/builder.py`
* In addition, it is best to include the words `llava`, `qwen` and `lora` in the weight name. For example, my name is `llava_next_endo_qwen_lora`. Because in most cases, the llava series will search for the corresponding model based on the name.
```
def lxr_load_llava_next_ov(model_path, model_base, model_name, load_8bit=False, load_4bit=False, device_map="auto", attn_implementation="flash_attention_2", customized_config=None, overwrite_config=None, **kwargs):
    kwargs["device_map"] = device_map
    kwargs["torch_dtype"] = torch.float16

    tokenizer = AutoTokenizer.from_pretrained(model_path)
    model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)

    rank0_print(f"Model Class: {model.__class__.__name__}")
    image_processor = None

    if "llava" in model_name.lower():
        mm_use_im_start_end = getattr(model.config, "mm_use_im_start_end", False)
        mm_use_im_patch_token = getattr(model.config, "mm_use_im_patch_token", True)
        if mm_use_im_patch_token:
            tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)
        if mm_use_im_start_end:
            tokenizer.add_tokens([DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN], special_tokens=True)
        model.resize_token_embeddings(len(tokenizer))

        vision_tower = model.get_vision_tower()
        if not vision_tower.is_loaded:
            vision_tower.load_model(device_map=device_map)
        if device_map != "auto":
            vision_tower.to(device="cuda", dtype=torch.float16)
        image_processor = vision_tower.image_processor

    if hasattr(model.config, "max_sequence_length"):
        context_len = model.config.max_sequence_length
    elif hasattr(model.config, "max_position_embeddings"):
        context_len = model.config.max_position_embeddings
    elif hasattr(model.config, "tokenizer_model_max_length"):
        context_len = model.config.tokenizer_model_max_length
    else:
        context_len = 2048

    return tokenizer, model, image_processor, context_len

```

```
model_path = os.path.expanduser(args.model_path)
model_name = get_model_name_from_path(model_path)
from llava.model.builder import lxr_load_llava_next_ov,lxr_load_pretrained_model
tokenizer, model, image_processor, context_len = lxr_load_pretrained_model(model_path, args.model_base, model_name)
......
parser = argparse.ArgumentParser()
parser.add_argument("--model-path", type=str, default="LLaVA-NeXT/checkpoints/llava_next_endo_qwen_lora")
parser.add_argument("--model-base", type=str, default="LLaVA-NeXT/llava-onevision-qwen2-7b-ov")
```
* Good Luck! 
* If you find it useful, please give me a thumbs up.

**Comment by zhudongwork** [comment]
> lxr_load_llava_next_ov

Good job! I carefully reviewed the `load_pretrained_model` function and noticed that when the `model_name` includes "lora", there is a lack of processing logic for the Qwen series of models. Therefore, I added support for Qwen in `load_pretrained_model` to enable compatibility with Llava-One.


![image](https://github.com/user-attachments/assets/589e44e1-ab6c-4b0a-9495-8dac3c5d7ce0)

**Comment by zhudongwork** [comment]
elif "qwen" in model_name.lower():
        from llava.model.language_model.llava_qwen import LlavaQwenConfig
        if overwrite_config is not None:
            llava_cfg = LlavaQwenConfig.from_pretrained(model_path)
            rank0_print(f"Overwriting config with {overwrite_config}")
            for k, v in overwrite_config.items():
                setattr(llava_cfg, k, v)
            model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, config=llava_cfg, **kwargs)
        else:
            model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)

**Comment by zhudongwork** [comment]
> ```
> elif "qwen" in model_name.lower():
>     from llava.model.language_model.llava_qwen import LlavaQwenConfig
>     if overwrite_config is not None:
>         llava_cfg = LlavaQwenConfig.from_pretrained(model_path)
>         rank0_print(f"Overwriting config with {overwrite_config}")
>         for k, v in overwrite_config.items():
>             setattr(llava_cfg, k, v)
>         model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, config=llava_cfg, **kwargs)
>     else:
>         model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)
> ```

same as this pull  https://github.com/LLaVA-VL/LLaVA-NeXT/pull/277/files

**Comment by wade0604** [comment]
@lxr-1204  where is the function lxr_load_pretrained_model ?

**Comment by zedward23** [comment]
> > ```
> > elif "qwen" in model_name.lower():
> >     from llava.model.language_model.llava_qwen import LlavaQwenConfig
> >     if overwrite_config is not None:
> >         llava_cfg = LlavaQwenConfig.from_pretrained(model_path)
> >         rank0_print(f"Overwriting config with {overwrite_config}")
> >         for k, v in overwrite_config.items():
> >             setattr(llava_cfg, k, v)
> >         model = LlavaQwenForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, attn_implementation=attn_implementation, config=llava_cfg, **kwargs)
> >     else:
> >         model = LlavaQwenForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)
> > ```
> 
> same as this pull https://github.com/LLaVA-VL/LLaVA-NeXT/pull/277/files

Doesn't this just omit the lora_config entirely? You're just not setting the config flag. At this point are we will using the lora weights at all?

**Comment by zedward23** [comment]
> > > ```
> > > elif "qwen" in model_name.lower():
> > >     from llava.model.language_model.llava_qwen import LlavaQwenConfig
> > >     if overwrite_config is not None:
> > >         llava_cfg = LlavaQwenConfig.from_pretrained(model_path)
> > >         rank0_print(f"Overwriting config with {overwrite_config}")
> > >         for k, v in overwrite_config.items():
> > >             setattr(llava_cfg, k, v)
> > >         model = LlavaQwenForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, attn_implementation=attn_implementation, config=llava_cfg, **kwargs)
> > >     else:
> > >         model = LlavaQwenForCausalLM.from_pretrained(model_base, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)
> > > ```
> > 
> > 
> > same as this pull https://github.com/LLaVA-VL/LLaVA-NeXT/pull/277/files
> 
> @zhudongwork Doesn't this just omit the lora_config entirely? You're just not setting the config flag. At this point are we will using the lora weights at all?

I mean it seems to have worked. I just don't understand why :sweat_smile:

**Comment by lxr-1204** [comment]
> @lxr-1204 where is the function lxr_load_pretrained_model ?函数 lxr_load_pretrained_model 在哪里？

Right Here！https://github.com/LLaVA-VL/LLaVA-NeXT/issues/253#issuecomment-2406434035

**Comment by zyandtom** [comment]
anybody know how to merge lora weights in the middle ckpts? looks like middle ckpts are not the same as final step
<img width="1247" alt="image" src="https://github.com/user-attachments/assets/743cfc34-76f9-4e02-b7db-9a182e3488f3" />
<img width="1249" alt="image" src="https://github.com/user-attachments/assets/49d267ad-a8b6-4556-ac60-1e188f58a196" />

**Comment by 1170300714** [comment]
> 🎉 I might have solved this problem.
> 
> * I rewrote the merge method, you can use this method instead of `load_pretrained_model` in `LLaVA-NeXT/llava/model/builder.py`
> * In addition, it is best to include the words `llava`, `qwen` and `lora` in the weight name. For example, my name is `llava_next_endo_qwen_lora`. Because in most cases, the llava series will search for the corresponding model based on the name.
> 
> ```
> def lxr_load_llava_next_ov(model_path, model_base, model_name, load_8bit=False, load_4bit=False, device_map="auto", attn_implementation="flash_attention_2", customized_config=None, overwrite_config=None, **kwargs):
>     kwargs["device_map"] = device_map
>     kwargs["torch_dtype"] = torch.float16
> 
>     tokenizer = AutoTokenizer.from_pretrained(model_path)
>     model = LlavaQwenForCausalLM.from_pretrained(model_path, low_cpu_mem_usage=True, attn_implementation=attn_implementation, **kwargs)
> 
>     rank0_print(f"Model Class: {model.__class__.__name__}")
>     image_processor = None
> 
>     if "llava" in model_name.lower():
>         mm_use_im_start_end = getattr(model.config, "mm_use_im_start_end", False)
>         mm_use_im_patch_token = getattr(model.config, "mm_use_im_patch_token", True)
>         if mm_use_im_patch_token:
>             tokenizer.add_tokens([DEFAULT_IMAGE_PATCH_TOKEN], special_tokens=True)
>         if mm_use_im_start_end:
>             tokenizer.add_tokens([DEFAULT_IM_START_TOKEN, DEFAULT_IM_END_TOKEN], special_tokens=True)
>         model.resize_token_embeddings(len(tokenizer))
> 
>         vision_tower = model.get_vision_tower()
>         if not vision_tower.is_loaded:
>             vision_tower.load_model(device_map=device_map)
>         if device_map != "auto":
>             vision_tower.to(device="cuda", dtype=torch.float16)
>         image_processor = vision_tower.image_processor
> 
>     if hasattr(model.config, "max_sequence_length"):
>         context_len = model.config.max_sequence_length
>     elif hasattr(model.config, "max_position_embeddings"):
>         context_len = model.config.max_position_embeddings
>     elif hasattr(model.config, "tokenizer_model_max_length"):
>         context_len = model.config.tokenizer_model_max_length
>     else:
>         context_len = 2048
> 
>     return tokenizer, model, image_processor, context_len
> ```
> 
> ```
> model_path = os.path.expanduser(args.model_path)
> model_name = get_model_name_from_path(model_path)
> from llava.model.builder import lxr_load_llava_next_ov,lxr_load_pretrained_model
> tokenizer, model, image_processor, context_len = lxr_load_pretrained_model(model_path, args.model_base, model_name)
> ......
> parser = argparse.ArgumentParser()
> parser.add_argument("--model-path", type=str, default="LLaVA-NeXT/checkpoints/llava_next_endo_qwen_lora")
> parser.add_argument("--model-base", type=str, default="LLaVA-NeXT/llava-onevision-qwen2-7b-ov")
> ```
> 
> * Good Luck!
> * If you find it useful, please give me a thumbs up.

Hello, Thanks for your contributions! But, it  seems that this code doesn't load the model_base (e.g. pretrained llava-ov ckpt), right? And,  if model_path indicates the path of lora ckpt dir, when running tokenizer = AutoTokenizer.from_pretrained(model_path), it will get a error that "can't load tokenizer for xxxx(this path)"

**Comment by cui0711** [comment]
After I added the logic related to the qwen model, the model still outputs garbled characters. 
<img width="878" alt="Image" src="https://github.com/user-attachments/assets/75985a46-abc6-4dd5-a7c7-d0f976c50bc5" />
<img width="1116" alt="Image" src="https://github.com/user-attachments/assets/51bb0d4f-e2c8-4155-9542-604da784c402" />

**Comment by 1170300714** [comment]
收到，感谢您的来件
