### ISSUE TITLE
libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kingofolk** [LLaVA-VL/LLaVA-NeXT#308]
Hi!

When I try to run the _finetune_ov.sh_ file, the following error occurs. How could I solve it? Btw, my cuda version is 12.4. Thanks a lot.

BASE_RUN_NAME: llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mlp2x_gelu-pretrain_blip558k_plain
PREV_STAGE_CHECKPOINT: /mnt/bn/vl-research/checkpoints/onevision/llavanext-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-mid_to_final_next_3m_am9_july14
MID_RUN_NAME: llava-onevision-google_siglip-so400m-patch14-384-Qwen_Qwen2-7B-Instruct-ov_stage_am9
Failed to import llava_llama from llava.language_model.llava_llama. Error: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory
Failed to import llava_qwen from llava.language_model.llava_qwen. Error: Failed to import transformers.models.llama.modeling_llama because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory
Failed to import llava_mistral from llava.language_model.llava_mistral. Error: Failed to import transformers.models.mistral.modeling_mistral because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory
Failed to import llava_mixtral from llava.language_model.llava_mixtral. Error: Failed to import transformers.models.mixtral.modeling_mixtral because of the following error (look up to see its traceback):
libcudart.so.11.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/hdd2/code/LLaVA-NeXT-main/llava/train/train_mem.py", line 1, in <module>
    from llava.train.train import train
  File "/hdd2/code/LLaVA-NeXT-main/llava/__init__.py", line 1, in <module>
    from .model import LlavaLlamaForCausalLM
ImportError: cannot import name 'LlavaLlamaForCausalLM' from 'llava.model' (/hdd2/code/LLaVA-NeXT-main/llava/model/__init__.py)

**Comment by AngelAlita** [comment]
hi, i also meet this problem, did you solve it?
