### ISSUE TITLE
Llama 3 tokenizer is not available. Make sure you have the necessary permissions.

### ISSUE THREAD

**Issue by overwhelmedxh** [LLaVA-VL/LLaVA-NeXT#330]
When I tried to run the code [here](https://github.com/LLaVA-VL/LLaVA-NeXT/blob/main/docs/LLaVA-NeXT.md), I encountered the following problem:

```
Traceback (most recent call last):
  File "/home/user/MLLM/LLaVA-NeXT/test.py", line 37, in <module>
    prompt_question = conv.get_prompt()
  File "/home/user/MLLM/LLaVA-NeXT/llava/conversation.py", line 99, in get_prompt
    raise ValueError("Llama 3 tokenizer is not available. Make sure you have the necessary permissions.")
ValueError: Llama 3 tokenizer is not available. Make sure you have the necessary permissions.
```

Anyone here encountered the same problem?

**Comment by queng12322** [comment]
I meet the same problem, have you solve it?

**Comment by queng12322** [comment]
i solved it, u have to get the permission for [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) first to use it. i hope this can help u!

**Comment by sjghh** [comment]
> i solved it, u have to get the permission for [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) first to use it. i hope this can help u!
How did you solve this issue? I need to change the _name_or_path to "/mnt/bn/vl-research-boli01-cn/workspace/zzz/projects/zzz/llava_next/project_checkpoints/llavanext-openai_clip-vit-large-patch14-336-meta-llama_Meta-Llama-3-8B-Instruct-blip558k_pretrain_plain_unmask_special_tokens", should I change it to llama3? My concern is whether I need to download llama3. I look forward to your response.

**Comment by sjghh** [comment]
> i solved it, u have to get the permission for [meta-llama/Meta-Llama-3-8B-Instruct](https://huggingface.co/meta-llama/Meta-Llama-3-8B-Instruct) first to use it. i hope this can help u!

How did you solve this issue? I need to change the _name_or_path to "/mnt/bn/vl-research-boli01-cn/workspace/zzz/projects/zzz/llava_next/project_checkpoints/llavanext-openai_clip-vit-large-patch14-336-meta-llama_Meta-Llama-3-8B-Instruct-blip558k_pretrain_plain_unmask_special_tokens", should I change it to llama3? My concern is whether I need to download llama3. I look forward to your response.

**Comment by queng12322** [comment]
@sjghh i did't change anything, i just get the permission to llama3 on huggingface and login my token

**Comment by sjghh** [comment]
> @sjghh i did't change anything, i just get the permission to llama3 on huggingface and login my token

Here is the translation of your message into English:

"I used this inference code, and even after adding this code, it still doesn't work:  
`from huggingface_hub import login`  
`login('hf_ENbIrEPQcbJvugMnhHxacOFxprVtEirVq')`  
Also, I have ensured that the token has permission to download Llama3. Could you tell me which weights you downloaded during inference?"

**Comment by sjghh** [comment]
> @sjghh i did't change anything, i just get the permission to llama3 on huggingface and login my token

I used this inference code, and even after adding this code, it still doesn't work:  
`from huggingface_hub import login`  
`login('hf_ENbIrEPQcbJvugMnhHxacOFxprVtEirVq')`  
Also, I have ensured that the token has permission to download Llama3. Could you tell me which weights you downloaded during inference?

**Comment by queng12322** [comment]
@sjghh llama3-llava-next-8b-hf, if your country is blocked form hugging face,make sure you use a mirror,hope this can help u
