### ISSUE TITLE
Inference error of LLaVA-NeXT-Video-7B-DPO

### ISSUE THREAD

**Issue by qjq-111** [LLaVA-VL/LLaVA-NeXT#58]
When I run 
`bash scripts/video/demo/video_demo.sh ${the path of LLaVA-NeXT-Video-7B-DPO} vicuna_v1 32 2 True ${the path of video}`
I get the error

```
Can't set vocab_size with value 32000 for LlavaConfig {
  "_name_or_path": "model_zoo/LLM/vicuna/7B-V1.5",
  "architectures": [
    "LlavaLlamaForCausalLM"
  ],
  "attention_bias": false,
  "attention_dropout": 0.0,
  "bos_token_id": 1,
  "eos_token_id": 2,
  "freeze_mm_mlp_adapter": true,
  "freeze_mm_vision_resampler": false,
  "hidden_act": "silu",
  "hidden_size": 4096,
  "ignore_index": -100,
  "image_aspect_ratio": "anyres",
  "image_crop_resolution": 224,
  "image_grid_pinpoints": [
    [
      336,
      672
    ],
    [
      672,
      336
    ],
    [
      672,
      672
    ],
    [
      1008,
      336
    ],
    [
      336,
      1008
    ]
  ],
  "image_split_resolution": 224,
  "image_token_index": 32000,
  "initializer_range": 0.02,
  "intermediate_size": 11008,
  "max_position_embeddings": 4096,
  "mm_hidden_size": 1024,
  "mm_patch_merge_type": "spatial_unpad",
  "mm_projector_lr": null,
  "mm_projector_type": "mlp2x_gelu",
  "mm_resampler_type": "spatial_pool",
  "mm_spatial_pool_mode": "average",
  "mm_spatial_pool_out_channels": 1024,
  "mm_spatial_pool_stride": 2,
  "mm_use_im_patch_token": false,
  "mm_use_im_start_end": false,
  "mm_vision_select_feature": "patch",
  "mm_vision_select_layer": -2,
  "mm_vision_tower": "openai/clip-vit-large-patch14-336",
  "mm_vision_tower_lr": null,
  "model_type": "llava",
  "num_attention_heads": 32,
  "num_hidden_layers": 32,
  "num_key_value_heads": 32,
  "pad_token_id": 0,
  "patchify_video_feature": false,
  "pretraining_tp": 1,
  "projector_hidden_act": "gelu",
  "rms_norm_eps": 1e-05,
  "rope_scaling": null,
  "rope_theta": 10000.0,
  "text_config": {
    "model_type": "llama"
  },
  "tie_word_embeddings": false,
  "tokenizer_model_max_length": 4096,
  "tokenizer_padding_side": "right",
  "torch_dtype": "bfloat16",
  "transformers_version": "4.39.0",
  "tune_mm_mlp_adapter": false,
  "tune_mm_vision_resampler": false,
  "unfreeze_mm_vision_tower": false,
  "use_cache": true,
  "use_mm_proj": true,
  "vision_config": {
    "hidden_size": 1024,
    "image_size": 336,
    "intermediate_size": 4096,
    "model_type": "clip_vision_model",
    "num_attention_heads": 16,
    "num_hidden_layers": 24,
    "patch_size": 14,
    "projection_dim": 768,
    "vocab_size": 32000
  },
  "vision_feature_layer": -2,
  "vision_feature_select_strategy": "default"
}

Traceback (most recent call last):
  File "/home/users/jiaqi.quan/LLaVA-NeXT/playground/demo/video_demo.py", line 183, in <module>
    run_inference(args)
  File "/home/users/jiaqi.quan/LLaVA-NeXT/playground/demo/video_demo.py", line 89, in run_inference
    cfg_pretrained = AutoConfig.from_pretrained(args.model_path)
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 1162, in from_pretrained
    return config_class.from_dict(config_dict, **unused_kwargs)
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/configuration_utils.py", line 761, in from_dict
    config = cls(**config_dict)
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/models/llava/configuration_llava.py", line 140, in __init__
    super().__init__(**kwargs)
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/configuration_utils.py", line 375, in __init__
    raise err
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/configuration_utils.py", line 372, in __init__
    setattr(self, key, value)
  File "/home/users/jiaqi.quan/miniconda3/envs/llava-next/lib/python3.10/site-packages/transformers/configuration_utils.py", line 258, in __setattr__
    super().__setattr__(key, value)
AttributeError: can't set attribute 'vocab_size'
```

The version of transformers is 4.39.0

**Comment by VenusHui** [comment]
I encountered the same problem, with transformers 4.43.0

**Comment by VenusHui** [comment]
I fixed it by setting conv_mode to the corresponding mode, all mode is shown below:
{
    "default": conv_vicuna_v0,
    "v0": conv_vicuna_v0,
    "v1": conv_vicuna_v1,
    "vicuna_v1": conv_vicuna_v1,
    "llama_2": conv_llama_2,
    "mistral_instruct": conv_mistral_instruct,
    "mistral_orca": conv_mistral_orca,
    "mistral_zephyr": conv_mistral_zephyr,
    "mistral_direct": conv_mistral_direct,
    "plain": conv_llava_plain,
    "v0_plain": conv_llava_plain,
    "chatml_direct": conv_chatml_direct,
    "llava_v0": conv_llava_v0,
    "llava_v0_mmtag": conv_llava_v0_mmtag,
    "llava_v1": conv_llava_v1,
    "llava_v1_mmtag": conv_llava_v1_mmtag,
    "llava_llama_2": conv_llava_llama_2,
    "llava_llama_3": conv_llava_llama_3,
    "llava_llama_2_simple": conv_llava_llama_2_simple,
    "llava_llama_2_mmtag": conv_llava_llama_2_mmtag,
    "llava_mistral_instruct": conv_mistral_instruct,
    "mpt": conv_mpt,
    "qwen_1_5": conv_qwen,
    "qwen_2": conv_qwen,
    "gemma_instruct": conv_gemma_instruct,
}
