### ISSUE TITLE
SGLang example not working: KeyError: 'answer'

### ISSUE THREAD

**Issue by k-nearest-neighbor** [LLaVA-VL/LLaVA-NeXT#86]
Following the SGLang instructions on the README.md

```
root@C.11313180:~/sglang$ bash examples/usage/llava_video/srt_example_llava_v.sh K 0 /root/sglang/examples/usage/llava_video/videos/Q98Z4OTh8RwmDonc.mp4 /root/models/LLaVA-NeXT-Video-7B-DPO 16
examples/usage/llava_video
Each video you will sample 16 frames
Number of GPUs in GPULIST: 8
1
Chunk 0 will run on GPUs 0
Running chunk 0 on GPUs 0 with port 31233. Attempt 1
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
[W socket.cpp:464] [c10d] The server socket cannot be initialized on [::]:31237 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:697] [c10d] The client socket cannot be initialized to connect to [::ffff:127.0.0.1]:31237 (errno: 97 - Address family not supported by protocol).
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
target_frames: 16
691it [00:24, 28.21it/s]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
chat template: vicuna_v1.1

========== single ==========

/root/sglang/examples/usage/llava_video/videos/Q98Z4OTh8RwmDonc.mp4
Traceback (most recent call last):
  File "/root/sglang/examples/usage/llava_video/srt_example_llava_v.py", line 192, in <module>
    single(cur_video, num_frames)
  File "/root/sglang/examples/usage/llava_video/srt_example_llava_v.py", line 25, in single
    print(state["answer"], "\n")
  File "/opt/conda/lib/python3.10/site-packages/sglang/lang/interpreter.py", line 844, in __getitem__
    return self.get_var(name)
  File "/opt/conda/lib/python3.10/site-packages/sglang/lang/interpreter.py", line 831, in get_var
    return self.stream_executor.get_var(name)
  File "/opt/conda/lib/python3.10/site-packages/sglang/lang/interpreter.py", line 252, in get_var
    return self.variables[name]
KeyError: 'answer'
```

**Comment by AllenDun** [comment]
also error for "https://github.com/sgl-project/sglang/blob/main/examples/usage/llava/srt_llava_next_test.py"; there may be dependency problem when installing sglang and llava-next (since llava-next use fixed version dependencies, not for sglang)
